name: release

on:
  push:
    branches:
      - master

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
          
      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - run: npm i -g pnpm
      - run: pnpm install
      - run: pnpm build
      - run: pnpm test

      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@master
        with:
          version: pnpm release:version-packages
          publish: pnpm release:from-packages
          commit: "chore(release): %s"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
