name: release

on:
  push:
    branches:
      - master

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2.1.5
        with:
          node-version: "14"

      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - run: npm i -g pnpm
      - run: pnpm install
      - run: pnpm install:monobundle
      - run: pnpm test

      - run: git add . && git reset --hard

      - run: pnpm release:from-package
