name: release

on:
  push:
    branches:
      - master

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2.1.5
        with:
          node-version: "15.x"

      - run: npm i -g pnpm
      - run: pnpm install
      - run: pnpm install:monobundle
      - run: pnpm test

      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@master
        with:
          version: pnpm release:version-packages
          publish: pnpm release:from-pacakges
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
